# Generated by Django 3.2.8 on 2021-11-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='introduction',
            field=models.TextField(blank=True, default='よろしくお願いします！', null=True, verbose_name='自己紹介'),
        ),
    ]
