# Generated by Django 3.2.8 on 2021-12-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/', verbose_name='画像'),
        ),
    ]
