# Generated by Django 3.2.8 on 2022-01-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_expopushtoken_expo_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expopushtoken',
            name='expo_token',
            field=models.CharField(default='', max_length=50),
        ),
    ]
