# Generated by Django 3.2.8 on 2022-01-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_expopushtoken'),
        ('matching_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkroom',
            name='expo_tokens',
            field=models.ManyToManyField(to='accounts.ExpoPushToken', verbose_name='EXPOトークン'),
        ),
    ]
