# Generated by Django 3.2.8 on 2022-01-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_expopushtoken_expo_token'),
        ('matching_app', '0002_talkroom_expo_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkroom',
            name='expo_tokens',
            field=models.ManyToManyField(blank=True, to='accounts.ExpoPushToken', verbose_name='EXPOトークン'),
        ),
    ]
