# Generated by Django 3.2.8 on 2022-01-31 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching_app', '0003_alter_talkroom_expo_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkroom',
            name='guest_user',
            field=models.ManyToManyField(blank=True, related_name='guest_user', to=settings.AUTH_USER_MODEL, verbose_name='ゲストユーザー'),
        ),
    ]
